# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20160809_2048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set([('mainUser', 'secondaryUser')]),
        ),
    ]
