# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='ident',
            field=models.TextField(default=''),
        ),
    ]
